### ISSUE TITLE
有没有vue2的写法？

### ISSUE THREAD

**Issue by Pixel-Daze** [kenberkeley/vue-drag-drop-sort-demo#1]
在handleDrop中获取不到拖拽节点，目的地节点能获取到，this.vm获取到的对象不是正在拖拽的实例

**Comment by kenberkeley** [comment]
本组件仅针对 Vue 1.x，若您需要适配 Vue 2.x，则需要 `handleDragStart` 中的 `this` 全局化（例如 `window._DRAG_NODE_ = this`），而不是通过 `vm.sync` 同步到所有的实例

本 demo 的灵感来源：https://www.v2ex.com/t/300047 就是用到上述全局变量的做法

**Comment by Pixel-Daze** [comment]
嗯，谢谢，sync在Vue2.x被取消了，没注意，我想想其他办法

**Comment by kenberkeley** [comment]
https://github.com/kenberkeley/vue2-drag-and-drop-demo
