### ISSUE TITLE
拖拽时抛错

### ISSUE THREAD

**Issue by RobertM574** [kenberkeley/vue-drag-drop-sort-demo#2]
`Uncaught TypeError: Cannot read property '$parent' of null`
定位错误位置
![image](https://user-images.githubusercontent.com/19481711/30894553-02561fc0-a377-11e7-86c9-b4d149f8d865.png)
组件引入：
![image](https://user-images.githubusercontent.com/19481711/30894574-318f3074-a377-11e7-85f7-17124e59b159.png)

**Comment by kenberkeley** [comment]
打个断点调试一下？

**Comment by kenberkeley** [comment]
要不像 https://www.v2ex.com/t/300047 那样，把 vm 挂载到 window 上？

**Comment by kenberkeley** [comment]
对了，本 demo 仅供 Vue 1.x 使用

**Comment by RobertM574** [comment]
![image](https://user-images.githubusercontent.com/19481711/30894706-cb7ab26c-a377-11e7-9224-86b8e78e2077.png)
打断点是时候发现，this.vm.$parent是存在的，不知道什么情况

**Comment by RobertM574** [comment]
哦哦，vue1.0之前没有接触过，需要怎么改造下么？？求教

**Comment by kenberkeley** [comment]
果然是 Vue 1.x 才报错

**Comment by kenberkeley** [comment]
把本 demo 升级到 Vue 2.x 可用，请参考 https://cn.vuejs.org/v2/guide/migration.html

**Comment by kenberkeley** [comment]
在这里比较关键的是用到了 Vue 1.x 的父子组件间的双向绑定 `.sync (twoWay)`

**Comment by RobertM574** [comment]
试验了 一上午，我用$emit 实现了双向绑定。migration做了vue1.x检测，更改了部分已经废弃的api，但是还是不行，仍然报那个错误，求问能否抽空兼容个vue 2.0 我会在组内推广下这个 插件

**Comment by kenberkeley** [comment]
试试这个方法共享状态就容易多了 https://github.com/kenberkeley/vue-state-management-alternative

**Comment by RobertM574** [comment]
我看看吧，主要还没理解这个插件的思路在哪里，

**Comment by kenberkeley** [comment]
https://github.com/kenberkeley/vue2-drag-and-drop-demo
